"""Delivery-fault injection for the mock payment gateway.

Implements five faults: a delayed webhook (0-45s), a duplicate delivery,
out-of-order delivery, a silent drop where the webhook never fires, and the
documented Failed-to-Authorized flip.

The flip appends a later `payment.authorized` event to the per-payment history
and never rewrites the earlier `payment.failed` entry. State resolution needs
both entries, each timestamped, to detect the flip and explain it.

Design note on time: delays are modelled as timestamps on a `deliver_at`
schedule against an injectable clock, not as real `sleep()` calls. A 45s delay
in a demo really does take 45s of wall-clock time; a test can drive the same
code path in microseconds with a fake clock. Nothing here sleeps.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Callable, List, Optional

from app.gateway.schemas import (
    ChaosConfig,
    ChaosMode,
    ErrorObject,
    WebhookEvent,
    WebhookEventName,
)


@dataclass
class ScheduledDelivery:
    """A webhook event plus the moment it is supposed to arrive."""

    event: WebhookEvent
    deliver_at: datetime


@dataclass
class DeliveryPlan:
    """What the injector decided should happen to a batch of webhook events.

    `dropped` events are the "silence" case -- they were generated by the
    gateway but will never be delivered. That silence is a signal in its own
    right rather than an absence of one, so dropped events are returned rather
    than discarded.
    """

    scheduled: List[ScheduledDelivery] = field(default_factory=list)
    dropped: List[WebhookEvent] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)


class ChaosInjector:
    """Turns a list of intended webhook events into a (possibly chaotic)
    delivery plan. Stateless with respect to payments -- the gateway owns all
    state; this class only decides *when and whether* events land."""

    def __init__(self, config: Optional[ChaosConfig] = None) -> None:
        self.config = config or ChaosConfig()

    # -- helpers ---------------------------------------------------------
    @property
    def modes(self) -> List[ChaosMode]:
        return list(self.config.modes)

    def has(self, mode: ChaosMode) -> bool:
        return mode in self.config.modes

    # -- main entry point ------------------------------------------------
    def apply(
        self,
        events: List[WebhookEvent],
        now: datetime,
        next_sequence: Callable[[], int],
        new_event_id: Callable[[str, int], str],
    ) -> DeliveryPlan:
        """Expand and schedule `events`.

        `next_sequence` / `new_event_id` are supplied by the gateway so the
        injector never has to mint identifiers or sequence numbers itself --
        sequence numbers stay monotonic per entity, which is what downstream
        idempotency depends on.
        """
        plan = DeliveryPlan()
        if not events:
            return plan

        working = list(events)

        # 1. Failed -> Authorized flip: append a later authorized event.
        if self.has(ChaosMode.FAILED_AUTHORIZED_FLIP):
            flips: List[WebhookEvent] = []
            for ev in working:
                if ev.event is WebhookEventName.PAYMENT_FAILED:
                    flips.append(self._build_flip_event(ev, now, next_sequence, new_event_id))
            if flips:
                working.extend(flips)
                plan.notes.append(
                    "failed_authorized_flip: appended {} late payment.authorized "
                    "event(s); the earlier payment.failed entry is preserved".format(len(flips))
                )
            else:
                plan.notes.append(
                    "failed_authorized_flip: requested but no payment.failed event to flip"
                )

        # 2. Silent drop: the webhook never fires at all.
        if self.has(ChaosMode.SILENT_DROP):
            plan.dropped.extend(working)
            plan.notes.append(
                "silent_drop: {} event(s) generated but never delivered; "
                "silence is the only signal downstream".format(len(working))
            )
            return plan

        # 3. Base schedule: an event arrives as soon as it happens. The flip
        #    event above happens in the future, so it must not be delivered at
        #    `now` just because everything else is.
        for ev in working:
            arrives = ev.webhook_received_at if ev.webhook_received_at > now else now
            plan.scheduled.append(ScheduledDelivery(event=ev, deliver_at=arrives))

        # 4. Delay: push arrival out by delay_seconds (0-45s).
        if self.has(ChaosMode.DELAYED_WEBHOOK):
            delay = self.config.delay_seconds
            for sd in plan.scheduled:
                sd.deliver_at = sd.deliver_at + timedelta(seconds=delay)
            plan.notes.append("delayed_webhook: arrival pushed out by {}s".format(delay))

        # 5. Out-of-order: reverse arrival order while leaving `sequence` and
        #    `occurred_at` untouched. Downstream must order by sequence, not by
        #    arrival -- that is the whole point of this mode.
        if self.has(ChaosMode.OUT_OF_ORDER_WEBHOOK):
            if len(plan.scheduled) >= 2:
                # Arrival times may all be identical, so reversing the list of
                # timestamps would be a no-op. Instead lay the events out on a
                # fresh millisecond-spaced timeline in reverse: the
                # highest-sequence event arrives first.
                base = min(sd.deliver_at for sd in plan.scheduled)
                spread = timedelta(milliseconds=1)
                count = len(plan.scheduled)
                for idx, sd in enumerate(plan.scheduled):
                    sd.deliver_at = base + spread * (count - 1 - idx)
                plan.notes.append(
                    "out_of_order_webhook: arrival order reversed across "
                    "{} events; sequence numbers unchanged".format(len(plan.scheduled))
                )
            else:
                plan.notes.append(
                    "out_of_order_webhook: requested but fewer than 2 events to reorder"
                )

        # 6. Duplicate delivery: same event_id and sequence, later arrival.
        #    Downstream must treat the second copy as a no-op.
        if self.has(ChaosMode.DUPLICATE_WEBHOOK):
            duplicates: List[ScheduledDelivery] = []
            for sd in plan.scheduled:
                dup = sd.event.model_copy(deep=True)
                dup.delivery_attempt = sd.event.delivery_attempt + 1
                dup.is_duplicate_delivery = True
                dup.webhook_received_at = sd.deliver_at + timedelta(
                    seconds=self.config.duplicate_after_seconds
                )
                dup.chaos_modes = list(dict.fromkeys(dup.chaos_modes + [ChaosMode.DUPLICATE_WEBHOOK]))
                duplicates.append(
                    ScheduledDelivery(
                        event=dup,
                        deliver_at=sd.deliver_at
                        + timedelta(seconds=self.config.duplicate_after_seconds),
                    )
                )
            plan.scheduled.extend(duplicates)
            plan.notes.append(
                "duplicate_webhook: {} duplicate delivery/deliveries appended "
                "with identical event_id + sequence".format(len(duplicates))
            )

        # 7. Stamp the final arrival timestamp onto every event.
        for sd in plan.scheduled:
            sd.event.webhook_received_at = sd.deliver_at
            sd.event.chaos_modes = list(dict.fromkeys(sd.event.chaos_modes + self.modes))
        for ev in plan.dropped:
            ev.chaos_modes = list(dict.fromkeys(ev.chaos_modes + self.modes))

        plan.scheduled.sort(key=lambda sd: sd.deliver_at)
        return plan

    # -- flip construction -----------------------------------------------
    def _build_flip_event(
        self,
        failed_event: WebhookEvent,
        now: datetime,
        next_sequence: Callable[[], int],
        new_event_id: Callable[[str, int], str],
    ) -> WebhookEvent:
        """Build the late `payment.authorized` that follows a `payment.failed`.

        This is the documented Razorpay case: a payment shows as Failed because
        of a bank/Razorpay communication gap (or a closed browser tab), then
        flips to Authorized once the delayed response arrives.
        """
        offset = timedelta(seconds=self.config.flip_after_seconds)
        seq = next_sequence()
        occurred = failed_event.occurred_at + offset
        return WebhookEvent(
            event_id=new_event_id(failed_event.entity_id, seq),
            entity_type=failed_event.entity_type,
            entity_id=failed_event.entity_id,
            event=WebhookEventName.PAYMENT_AUTHORIZED,
            sequence=seq,
            occurred_at=occurred,
            webhook_sent_at=occurred,
            webhook_received_at=occurred,
            delivery_attempt=1,
            is_duplicate_delivery=False,
            resulting_state="AUTHORIZED",
            error=None,
            chaos_modes=[ChaosMode.FAILED_AUTHORIZED_FLIP],
        )


def error_or_documented_default(error: Optional[ErrorObject]) -> ErrorObject:
    """Return the caller's error object, falling back to a documented example.

    The gateway never invents an error code.
    """
    from app.gateway.schemas import DOCUMENTED_EXAMPLE_ERROR

    return error if error is not None else DOCUMENTED_EXAMPLE_ERROR.model_copy(deep=True)
